### ISSUE TITLE
make string scrambler

### ISSUE THREAD

**Issue by KazakEz** [Rabies1337/Vox#2]
Connect to your project https://github.com/xxDark/StringScrambler please :D so that the strings in the game were not visible

**Comment by shift-jis** [comment]
May I ask for a more detailed explanation?

**Comment by zozotownmoment** [comment]
toshimichi have wine

**Comment by KazakEz** [comment]
> May I ask for a more detailed explanation?

Yes, here's the code that I sent you can remove strings from the game's memory, this is very useful, let's say they can't be found during a check through Process Hacker and they won't issue a ban

**Comment by shift-jis** [comment]
Okay, I'll consider it.

**Comment by zozotownmoment** [comment]
stfu you need wine

**Comment by zozotownmoment** [comment]
hello! finally. ihave wine!!!!!!!!!!

**Comment by KazakEz** [comment]
xdd sleep
